# Generated by Django 5.1.5 on 2025-01-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
