# Generated by Django 5.1.5 on 2025-01-28 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(360)], verbose_name='Комментарий'),
        ),
    ]
