# Generated by Django 5.1.5 on 2025-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='users/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
